[tox]
isolated_build = True
requires =
  tox-poetry-installer
envlist =
  py{38,39,310,311,312}-django{40,41,42}

[testenv]
allowlist_externals = poetry
commands_pre =
  poetry install -v
commands =
  pytest

[overrides]
django40 = "Django>=4.0,<4.1"
django41 = "Django>=4.1,<4.2"
django42 = "Django>=4.2,<4.3"
